language: node_js
node_js:
  - "10"
branches:
  only:
    - master
    - develop
before_install:
  # update yarn and npm
  - npm i npm -g
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
  - echo "npm $(npm -v)" && echo "yarn $(yarn -v)"
install:
  - yarn
jobs:
  include:
    - stage: test
      if: "type = pull_request"
      script:
        - yarn test
    - stage: publish
      if: "branch = master and type = push"
      script:
        - yarn deploy
cache: yarn
